# Generated by Django 2.2.3 on 2019-07-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190706_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(default='c++', max_length=30),
        ),
    ]
