# Generated by Django 2.2.3 on 2019-07-30 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillstaught',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Skill'),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('year', 'semester')},
        ),
        migrations.AddField(
            model_name='coursestaff',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
        migrations.AddField(
            model_name='coursestaff',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Instructor'),
        ),
        migrations.AddField(
            model_name='coursemember',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
        migrations.AddField(
            model_name='coursemember',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Student'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Semester'),
        ),
        migrations.AlterUniqueTogether(
            name='skillstaught',
            unique_together={('skill', 'course')},
        ),
    ]
